apiVersion: v1
kind: Secret
metadata:
  name: massivedecks-secrets
  namespace: massivedecks
type: Opaque
stringData:
  # Change this to a secure random value.
  # You can generate one by running: cd server && npm run generate-secret
  server-secret: "CHANGE ME"
  # Change this to a secure random value, and match it in server-config ConfigMap.
  postgres-password: "CHANGE ME"
